### ISSUE TITLE
IO BUSY问题

### ISSUE THREAD

**Issue by mushroom-x** [EasyMicroPython/EMP-IDE#1]
如果在Diconnect的情况下, 点击了save按钮.  没有响应, 然后我去connect之后, 再次save也会无效, 提示IO Busy. 
只有重新刷新页面之后, 才能解决这个问题.

**Comment by Singein** [comment]
Roger that.
________________________________
发件人: 阿凯-1Z实验室 <notifications@github.com>
发送时间: 2019年1月7日 11:44
收件人: Easy-MicroPython/EMP-IDE
抄送: Subscribed
主题: [Easy-MicroPython/EMP-IDE] IO BUSY问题 (#1)


如果在Diconnect的情况下, 点击了save按钮. 没有响应, 然后我去connect之后, 再次save也会无效, 提示IO Busy.
只有重新刷新页面之后, 才能解决这个问题.

―

**Comment by Singein** [comment]
如果是disconnect就把锁去掉。
